package com.minefus.degraduck.models.items;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRoyalBouftouSword extends ModelBase
{
    ModelRenderer one, two, three, four, five, six, seven, eight, nine, ten, twelve, eleven, thirteen, fourteen, fiveteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone, twentytwo, twentythree, twentyfour, twentyfive, twentysix, twentyseven, twentyeight, twentynine;

    public ModelRoyalBouftouSword()
    {
        textureWidth = 64;
        textureHeight = 32;
        one = new ModelRenderer(this, 28, 0);
        one.addBox(-1.0F, -3.0F, -1.0F, 2, 9, 2);
        one.setRotationPoint(0.0F, 20.0F, 0.0F);
        one.setTextureSize(64, 32);
        one.mirror = true;
        setRotation(one, 0.0F, 0.0F, 0.0F);
        two = new ModelRenderer(this, 40, 14);
        two.addBox(-1.5F, 2.5F, -1.5F, 3, 3, 3);
        two.setRotationPoint(0.0F, 20.0F, 0.0F);
        two.setTextureSize(64, 32);
        two.mirror = true;
        setRotation(two, 0.0F, 0.0F, 0.0F);
        three = new ModelRenderer(this, 40, 14);
        three.addBox(-1.0F, 3.0F, -2.0F, 2, 2, 4);
        three.setRotationPoint(0.0F, 20.0F, 0.0F);
        three.setTextureSize(64, 32);
        three.mirror = true;
        setRotation(three, 0.0F, 0.0F, 0.0F);
        four = new ModelRenderer(this, 40, 14);
        four.addBox(-2.0F, 3.0F, -1.0F, 4, 2, 2);
        four.setRotationPoint(0.0F, 20.0F, 0.0F);
        four.setTextureSize(64, 32);
        four.mirror = true;
        setRotation(four, 0.0F, 0.0F, 0.0F);
        five = new ModelRenderer(this, 37, 0);
        five.addBox(-1.5F, -6.0F, -5.0F, 3, 3, 10);
        five.setRotationPoint(0.0F, 20.0F, 0.0F);
        five.setTextureSize(64, 32);
        five.mirror = true;
        setRotation(five, 0.0F, 0.0F, 0.0F);
        six = new ModelRenderer(this, 55, 0);
        six.addBox(-1.0F, -5.0F, -5.5F, 2, 3, 2);
        six.setRotationPoint(0.0F, 20.0F, 0.0F);
        six.setTextureSize(64, 32);
        six.mirror = true;
        setRotation(six, 0.0F, 0.0F, 0.0F);
        seven = new ModelRenderer(this, 42, 0);
        seven.addBox(-0.5F, -2.5F, -5.0F, 1, 1, 1);
        seven.setRotationPoint(0.0F, 20.0F, 0.0F);
        seven.setTextureSize(64, 32);
        seven.mirror = true;
        setRotation(seven, 0.0F, 0.0F, 0.0F);
        eight = new ModelRenderer(this, 55, 0);
        eight.addBox(-1.0F, -5.0F, 3.5F, 2, 3, 2);
        eight.setRotationPoint(0.0F, 20.0F, 0.0F);
        eight.setTextureSize(64, 32);
        eight.mirror = true;
        setRotation(eight, 0.0F, 0.0F, 0.0F);
        nine = new ModelRenderer(this, 42, 0);
        nine.addBox(-0.5F, -2.5F, 4.0F, 1, 1, 1);
        nine.setRotationPoint(0.0F, 20.0F, 0.0F);
        nine.setTextureSize(64, 32);
        nine.mirror = true;
        setRotation(nine, 0.0F, 0.0F, 0.0F);
        ten = new ModelRenderer(this, 0, 0);
        ten.addBox(-1.0F, -26.0F, -1.0F, 2, 20, 2);
        ten.setRotationPoint(0.0F, 20.0F, 0.0F);
        ten.setTextureSize(64, 32);
        ten.mirror = true;
        setRotation(ten, 0.0F, 0.0F, 0.0F);
        twelve = new ModelRenderer(this, 0, 0);
        twelve.addBox(-0.5F, -23.0F, -3.5F, 1, 2, 7);
        twelve.setRotationPoint(0.0F, 20.0F, 0.0F);
        twelve.setTextureSize(64, 32);
        twelve.mirror = true;
        setRotation(twelve, 0.0F, 0.0F, 0.0F);
        eleven = new ModelRenderer(this, 0, 0);
        eleven.addBox(-0.5F, -7.0F, -4.0F, 1, 1, 8);
        eleven.setRotationPoint(0.0F, 20.0F, 0.0F);
        eleven.setTextureSize(64, 32);
        eleven.mirror = true;
        setRotation(eleven, 0.0F, 0.0F, 0.0F);
        thirteen = new ModelRenderer(this, 0, 0);
        thirteen.addBox(-0.5F, -28.0F, -1.0F, 1, 1, 2);
        thirteen.setRotationPoint(0.0F, 20.0F, 0.0F);
        thirteen.setTextureSize(64, 32);
        thirteen.mirror = true;
        setRotation(thirteen, 0.0F, 0.0F, 0.0F);
        fourteen = new ModelRenderer(this, 0, 0);
        fourteen.addBox(-0.5F, -24.0F, -3.0F, 1, 1, 6);
        fourteen.setRotationPoint(0.0F, 20.0F, 0.0F);
        fourteen.setTextureSize(64, 32);
        fourteen.mirror = true;
        setRotation(fourteen, 0.0F, 0.0F, 0.0F);
        fiveteen = new ModelRenderer(this, 0, 0);
        fiveteen.addBox(-0.5F, -11.0F, -3.5F, 1, 1, 7);
        fiveteen.setRotationPoint(0.0F, 20.0F, 0.0F);
        fiveteen.setTextureSize(64, 32);
        fiveteen.mirror = true;
        setRotation(fiveteen, 0.0F, 0.0F, 0.0F);
        sixteen = new ModelRenderer(this, 0, 0);
        sixteen.addBox(-0.5F, -10.0F, -4.0F, 1, 1, 8);
        sixteen.setRotationPoint(0.0F, 20.0F, 0.0F);
        sixteen.setTextureSize(64, 32);
        sixteen.mirror = true;
        setRotation(sixteen, 0.0F, 0.0F, 0.0F);
        seventeen = new ModelRenderer(this, 0, 0);
        seventeen.addBox(-0.5F, -9.0F, -4.5F, 1, 2, 9);
        seventeen.setRotationPoint(0.0F, 20.0F, 0.0F);
        seventeen.setTextureSize(64, 32);
        seventeen.mirror = true;
        setRotation(seventeen, 0.0F, 0.0F, 0.0F);
        eighteen = new ModelRenderer(this, 0, 0);
        eighteen.addBox(-0.5F, -21.0F, -3.0F, 1, 1, 6);
        eighteen.setRotationPoint(0.0F, 20.0F, 0.0F);
        eighteen.setTextureSize(64, 32);
        eighteen.mirror = true;
        setRotation(eighteen, 0.0F, 0.0F, 0.0F);
        nineteen = new ModelRenderer(this, 0, 0);
        nineteen.addBox(-0.5F, -20.0F, -2.5F, 1, 2, 5);
        nineteen.setRotationPoint(0.0F, 20.0F, 0.0F);
        nineteen.setTextureSize(64, 32);
        nineteen.mirror = true;
        setRotation(nineteen, 0.0F, 0.0F, 0.0F);
        twenty = new ModelRenderer(this, 0, 0);
        twenty.addBox(-0.5F, -13.0F, -3.0F, 1, 2, 6);
        twenty.setRotationPoint(0.0F, 20.0F, 0.0F);
        twenty.setTextureSize(64, 32);
        twenty.mirror = true;
        setRotation(twenty, 0.0F, 0.0F, 0.0F);
        twentyone = new ModelRenderer(this, 0, 0);
        twentyone.addBox(-0.5F, -14.0F, -3.5F, 1, 1, 7);
        twentyone.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentyone.setTextureSize(64, 32);
        twentyone.mirror = true;
        setRotation(twentyone, 0.0F, 0.0F, 0.0F);
        twentytwo = new ModelRenderer(this, 0, 0);
        twentytwo.addBox(-0.5F, -16.0F, -4.0F, 1, 2, 8);
        twentytwo.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentytwo.setTextureSize(64, 32);
        twentytwo.mirror = true;
        setRotation(twentytwo, 0.0F, 0.0F, 0.0F);
        twentythree = new ModelRenderer(this, 0, 0);
        twentythree.addBox(-0.5F, -17.0F, -3.5F, 1, 1, 7);
        twentythree.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentythree.setTextureSize(64, 32);
        twentythree.mirror = true;
        setRotation(twentythree, 0.0F, 0.0F, 0.0F);
        twentyfour = new ModelRenderer(this, 0, 0);
        twentyfour.addBox(-0.5F, -18.0F, -3.0F, 1, 1, 6);
        twentyfour.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentyfour.setTextureSize(64, 32);
        twentyfour.mirror = true;
        setRotation(twentyfour, 0.0F, 0.0F, 0.0F);
        twentyfive = new ModelRenderer(this, 0, 0);
        twentyfive.addBox(-0.5F, -25.0F, -2.5F, 1, 1, 5);
        twentyfive.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentyfive.setTextureSize(64, 32);
        twentyfive.mirror = true;
        setRotation(twentyfive, 0.0F, 0.0F, 0.0F);
        twentysix = new ModelRenderer(this, 0, 0);
        twentysix.addBox(-0.5F, -26.0F, -2.0F, 1, 1, 4);
        twentysix.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentysix.setTextureSize(64, 32);
        twentysix.mirror = true;
        setRotation(twentysix, 0.0F, 0.0F, 0.0F);
        twentyseven = new ModelRenderer(this, 0, 0);
        twentyseven.addBox(-1.0F, -28.0F, -0.5F, 2, 2, 1);
        twentyseven.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentyseven.setTextureSize(64, 32);
        twentyseven.mirror = true;
        setRotation(twentyseven, 0.0F, 0.0F, 0.0F);
        twentyeight = new ModelRenderer(this, 0, 0);
        twentyeight.addBox(-0.5F, -27.0F, -1.5F, 1, 1, 3);
        twentyeight.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentyeight.setTextureSize(64, 32);
        twentyeight.mirror = true;
        setRotation(twentyeight, 0.0F, 0.0F, 0.0F);
        twentynine = new ModelRenderer(this, 0, 0);
        twentynine.addBox(-0.5F, -29.0F, -0.5F, 1, 1, 1);
        twentynine.setRotationPoint(0.0F, 20.0F, 0.0F);
        twentynine.setTextureSize(64, 32);
        twentynine.mirror = true;
        setRotation(twentynine, 0.0F, 0.0F, 0.0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        one.render(f5);
        two.render(f5);
        three.render(f5);
        four.render(f5);
        five.render(f5);
        six.render(f5);
        seven.render(f5);
        eight.render(f5);
        nine.render(f5);
        ten.render(f5);
        twelve.render(f5);
        eleven.render(f5);
        thirteen.render(f5);
        fourteen.render(f5);
        fiveteen.render(f5);
        sixteen.render(f5);
        seventeen.render(f5);
        eighteen.render(f5);
        nineteen.render(f5);
        twenty.render(f5);
        twentyone.render(f5);
        twentytwo.render(f5);
        twentythree.render(f5);
        twentyfour.render(f5);
        twentyfive.render(f5);
        twentysix.render(f5);
        twentyseven.render(f5);
        twentyeight.render(f5);
        twentynine.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}