package fr.realfaction.benjaminloison.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelBlockForge extends ModelBase
{
    ModelRenderer un;
    ModelRenderer deux;
    ModelRenderer trois;
    ModelRenderer quatres;
    ModelRenderer cinq;
    ModelRenderer six;
    ModelRenderer sept;
    ModelRenderer huit;
    ModelRenderer neuf;
    ModelRenderer dix;
    ModelRenderer onze;
    ModelRenderer douze;
    ModelRenderer treize;
    ModelRenderer quatorze;
    ModelRenderer quinze;
    ModelRenderer seize;
    ModelRenderer dixsept;
    ModelRenderer dixneuf;
    ModelRenderer vingt;
    ModelRenderer vingtetun;
    ModelRenderer vingtdeux;
    ModelRenderer vingttrois;
    ModelRenderer vingtquatres;
    ModelRenderer vingtcinq;
    ModelRenderer vingtsix;
    ModelRenderer vingtsept;
    ModelRenderer vingthuit;
    ModelRenderer vingtneuf;
    ModelRenderer trente;
    ModelRenderer trenteetun;
    ModelRenderer trentedeux;
    ModelRenderer trentetrois;
    ModelRenderer trentequatres;
    ModelRenderer trentecinq;
    ModelRenderer trentesix;
    ModelRenderer trentesept;
    ModelRenderer trentehuit;
    ModelRenderer trenteneuf;
    ModelRenderer quarante;
    ModelRenderer quaranteetun;
    ModelRenderer quarantedeux;
    ModelRenderer quarantetrois;
    ModelRenderer quarantequatres;
    ModelRenderer quarantecinq;
    ModelRenderer quarantesix;
    ModelRenderer quarantesept;
    ModelRenderer quarantehuit;
  
  public ModelBlockForge()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      un = new ModelRenderer(this, 18, 27);
      un.addBox(0F, 0F, 0F, 22, 8, 1);
      un.setRotationPoint(-11F, 8F, 13F);
      un.setTextureSize(128, 64);
      setRotation(un, 0F, 0F, 0F);
      deux = new ModelRenderer(this, 18, 27);
      deux.addBox(0F, 0F, 0F, 1, 8, 24);
      deux.setRotationPoint(-13F, 8F, -12F);
      deux.setTextureSize(128, 64);
      setRotation(deux, 0F, 0F, 0F);
      trois = new ModelRenderer(this, 18, 27);
      trois.addBox(0F, 0F, 0F, 22, 8, 1);
      trois.setRotationPoint(-11F, 8F, -14F);
      trois.setTextureSize(128, 64);
      setRotation(trois, 0F, 0F, 0F);
      quatres = new ModelRenderer(this, 18, 27);
      quatres.addBox(0F, 0F, 0F, 1, 8, 22);
      quatres.setRotationPoint(13F, 8F, -11F);
      quatres.setTextureSize(128, 64);
      setRotation(quatres, 0F, 0F, 0F);
      cinq = new ModelRenderer(this, 15, 30);
      cinq.addBox(0F, 0F, 0F, 1, 8, 26);
      cinq.setRotationPoint(11F, 8F, -13F);
      cinq.setTextureSize(128, 64);
      setRotation(cinq, 0F, 0F, 0F);
      six = new ModelRenderer(this, 49, 0);
      six.addBox(0F, 0F, 0F, 1, 8, 22);
      six.setRotationPoint(16F, 16F, -11F);
      six.setTextureSize(128, 64);
      setRotation(six, 0F, 0F, 0F);
      sept = new ModelRenderer(this, 78, 0);
      sept.addBox(0F, 0F, 0F, 1, 8, 24);
      sept.setRotationPoint(15F, 16F, -12F);
      sept.setTextureSize(128, 64);
      setRotation(sept, 0F, 0F, 0F);
      huit = new ModelRenderer(this, 74, 0);
      huit.addBox(0F, 0F, 0F, 1, 8, 26);
      huit.setRotationPoint(14F, 16F, -13F);
      huit.setTextureSize(128, 64);
      setRotation(huit, 0F, 0F, 0F);
      neuf = new ModelRenderer(this, 0, 0);
      neuf.addBox(0F, 0F, 0F, 1, 7, 6);
      neuf.setRotationPoint(3F, 9F, -20F);
      neuf.setTextureSize(128, 64);
      setRotation(neuf, 0F, 0F, 0F);
      dix = new ModelRenderer(this, 0, 11);
      dix.addBox(0F, 0F, 0F, 24, 8, 1);
      dix.setRotationPoint(-12F, 16F, -16F);
      dix.setTextureSize(128, 64);
      setRotation(dix, 0F, 0F, 0F);
      onze = new ModelRenderer(this, 8, 18);
      onze.addBox(0F, 0F, 0F, 26, 8, 1);
      onze.setRotationPoint(-13F, 16F, -15F);
      onze.setTextureSize(128, 64);
      setRotation(onze, 0F, 0F, 0F);
      douze = new ModelRenderer(this, 0, 0);
      douze.addBox(0F, 0F, 0F, 22, 8, 1);
      douze.setRotationPoint(-11F, 16F, 16F);
      douze.setTextureSize(128, 64);
      setRotation(douze, 0F, 0F, 0F);
      treize = new ModelRenderer(this, 0, 0);
      treize.addBox(0F, 0F, 0F, 24, 8, 1);
      treize.setRotationPoint(-12F, 16F, 15F);
      treize.setTextureSize(128, 64);
      setRotation(treize, 0F, 0F, 0F);
      quatorze = new ModelRenderer(this, 78, 52);
      quatorze.addBox(0F, 0F, 0F, 14, 8, 3);
      quatorze.setRotationPoint(-7F, -16F, 6.5F);
      quatorze.setTextureSize(128, 64);
      setRotation(quatorze, 0F, 0F, 0F);
      quinze = new ModelRenderer(this, 0, 0);
      quinze.addBox(0F, 0F, 0F, 26, 8, 1);
      quinze.setRotationPoint(-13F, 16F, 14F);
      quinze.setTextureSize(128, 64);
      setRotation(quinze, 0F, 0F, 0F);
      seize = new ModelRenderer(this, 69, 0);
      seize.addBox(0F, 0F, 0F, 1, 8, 22);
      seize.setRotationPoint(-17F, 16F, -11F);
      seize.setTextureSize(128, 64);
      setRotation(seize, 0F, 0F, 0F);
      dixsept = new ModelRenderer(this, 78, 0);
      dixsept.addBox(0F, 0F, 0F, 1, 8, 24);
      dixsept.setRotationPoint(-16F, 16F, -12F);
      dixsept.setTextureSize(128, 64);
      setRotation(dixsept, 0F, 0F, 0F);
      dixneuf = new ModelRenderer(this, 74, 0);
      dixneuf.addBox(0F, 0F, 0F, 1, 8, 26);
      dixneuf.setRotationPoint(-15F, 16F, -13F);
      dixneuf.setTextureSize(128, 64);
      setRotation(dixneuf, 0F, 0F, 0F);
      vingt = new ModelRenderer(this, 16, -9);
      vingt.addBox(0F, 0F, 0F, 28, 1, 28);
      vingt.setRotationPoint(-14F, 16F, -14F);
      vingt.setTextureSize(128, 64);
      setRotation(vingt, 0F, 0F, 0F);
      vingtetun = new ModelRenderer(this, 18, 30);
      vingtetun.addBox(0F, 0F, 0F, 23, 8, 26);
      vingtetun.setRotationPoint(-12F, 8F, -13F);
      vingtetun.setTextureSize(128, 64);
      setRotation(vingtetun, 0F, 0F, 0F);
      vingtdeux = new ModelRenderer(this, 77, 39);
      vingtdeux.addBox(0F, 0F, 0F, 14, 8, 3);
      vingtdeux.setRotationPoint(-7F, -16F, -9.5F);
      vingtdeux.setTextureSize(128, 64);
      setRotation(vingtdeux, 0F, 0F, 0F);
      vingttrois = new ModelRenderer(this, 74, 39);
      vingttrois.addBox(0F, 0F, 0F, 3, 8, 17);
      vingttrois.setRotationPoint(5F, -16F, -8.5F);
      vingttrois.setTextureSize(128, 64);
      setRotation(vingttrois, 0F, 0F, 0F);
      vingtquatres = new ModelRenderer(this, 71, 39);
      vingtquatres.addBox(0F, 0F, 0F, 3, 8, 17);
      vingtquatres.setRotationPoint(-8F, -16F, -8.5F);
      vingtquatres.setTextureSize(128, 64);
      setRotation(vingtquatres, 0F, 0F, 0F);
      vingtcinq = new ModelRenderer(this, 24, 38);
      vingtcinq.addBox(0F, 0F, 0F, 18, 16, 4);
      vingtcinq.setRotationPoint(-9F, -8F, -11.5F);
      vingtcinq.setTextureSize(128, 64);
      setRotation(vingtcinq, 0F, 0F, 0F);
      vingtsix = new ModelRenderer(this, 18, 27);
      vingtsix.addBox(0F, 0F, 0F, 4, 16, 21);
      vingtsix.setRotationPoint(-10F, -8F, -10.5F);
      vingtsix.setTextureSize(128, 64);
      setRotation(vingtsix, 0F, 0F, 0F);
      vingtsept = new ModelRenderer(this, 18, 27);
      vingtsept.addBox(0F, 0F, 0F, 18, 16, 4);
      vingtsept.setRotationPoint(-9F, -8F, 7.5F);
      vingtsept.setTextureSize(128, 64);
      setRotation(vingtsept, 0F, 0F, 0F);
      vingthuit = new ModelRenderer(this, 18, 27);
      vingthuit.addBox(0F, 0F, 0F, 4, 16, 21);
      vingthuit.setRotationPoint(6F, -8F, -10.5F);
      vingthuit.setTextureSize(128, 64);
      setRotation(vingthuit, 0F, 0F, 0F);
      vingtneuf = new ModelRenderer(this, 72, 20);
      vingtneuf.addBox(0F, 0F, 0F, 22, 8, 1);
      vingtneuf.setRotationPoint(-11F, 16F, -17F);
      vingtneuf.setTextureSize(128, 64);
      setRotation(vingtneuf, 0F, 0F, 0F);
      trente = new ModelRenderer(this, 0, 0);
      trente.addBox(0F, 0F, 0F, 10, 6, 8);
      trente.setRotationPoint(-5F, 18F, -25F);
      trente.setTextureSize(128, 64);
      setRotation(trente, 0F, 0F, 0F);
      trenteetun = new ModelRenderer(this, 0, 0);
      trenteetun.addBox(0F, 0F, 0F, 10, 2, 2);
      trenteetun.setRotationPoint(-5F, 16F, -25F);
      trenteetun.setTextureSize(128, 64);
      setRotation(trenteetun, 0F, 0F, 0F);
      trentedeux = new ModelRenderer(this, 2, 57);
      trentedeux.addBox(0F, 0F, 0F, 1, 5, 2);
      trentedeux.setRotationPoint(1F, 12F, -21F);
      trentedeux.setTextureSize(128, 64);
      setRotation(trentedeux, 0F, 0F, 0F);
      trentetrois = new ModelRenderer(this, 0, 0);
      trentetrois.addBox(0F, 0F, 0F, 2, 2, 6);
      trentetrois.setRotationPoint(3F, 16F, -23F);
      trentetrois.setTextureSize(128, 64);
      setRotation(trentetrois, 0F, 0F, 0F);
      trentequatres = new ModelRenderer(this, 0, 0);
      trentequatres.addBox(0F, 0F, 0F, 2, 2, 6);
      trentequatres.setRotationPoint(-5F, 16F, -23F);
      trentequatres.setTextureSize(128, 64);
      setRotation(trentequatres, 0F, 0F, 0F);
      trentecinq = new ModelRenderer(this, 0, 0);
      trentecinq.addBox(0F, 0F, 0F, 1, 1, 6);
      trentecinq.setRotationPoint(-5F, 8F, -20F);
      trentecinq.setTextureSize(128, 64);
      setRotation(trentecinq, 0F, 0F, 0F);
      trentesix = new ModelRenderer(this, 0, 0);
      trentesix.addBox(0F, 0F, 0F, 8, 2, 8);
      trentesix.setRotationPoint(-4F, 7F, -20F);
      trentesix.setTextureSize(128, 64);
      setRotation(trentesix, 0F, 0F, 0F);
      trentesept = new ModelRenderer(this, 2, 57);
      trentesept.addBox(0F, 0F, 0F, 4, 1, 4);
      trentesept.setRotationPoint(-2F, 17F, -22F);
      trentesept.setTextureSize(128, 64);
      setRotation(trentesept, 0F, 0F, 0F);
      trentehuit = new ModelRenderer(this, 5, 57);
      trentehuit.addBox(0F, 0F, 0F, 4, 5, 1);
      trentehuit.setRotationPoint(-2F, 12F, -22F);
      trentehuit.setTextureSize(128, 64);
      setRotation(trentehuit, 0F, 0F, 0F);
      trenteneuf = new ModelRenderer(this, 2, 57);
      trenteneuf.addBox(0F, 0F, 0F, 4, 5, 1);
      trenteneuf.setRotationPoint(-2F, 12F, -19F);
      trenteneuf.setTextureSize(128, 64);
      setRotation(trenteneuf, 0F, 0F, 0F);
      quarante = new ModelRenderer(this, 7, 56);
      quarante.addBox(0F, 0F, 0F, 4, 5, 1);
      quarante.setRotationPoint(-2F, 12F, -22F);
      quarante.setTextureSize(128, 64);
      setRotation(quarante, 0F, 0F, 0F);
      quaranteetun = new ModelRenderer(this, 2, 57);
      quaranteetun.addBox(0F, 0F, 0F, 1, 5, 2);
      quaranteetun.setRotationPoint(-2F, 12F, -21F);
      quaranteetun.setTextureSize(128, 64);
      setRotation(quaranteetun, 0F, 0F, 0F);
      quarantedeux = new ModelRenderer(this, 5, 56);
      quarantedeux.addBox(0F, 0F, 0F, 4, 5, 1);
      quarantedeux.setRotationPoint(-2F, 12F, -22F);
      quarantedeux.setTextureSize(128, 64);
      setRotation(quarantedeux, 0F, 0F, 0F);
      quarantetrois = new ModelRenderer(this, 0, 0);
      quarantetrois.addBox(0F, 0F, 0F, 1, 8, 6);
      quarantetrois.setRotationPoint(4F, 8F, -20F);
      quarantetrois.setTextureSize(128, 64);
      setRotation(quarantetrois, 0F, 0F, 0F);
      quarantequatres = new ModelRenderer(this, 0, 0);
      quarantequatres.addBox(0F, 0F, 0F, 2, 7, 6);
      quarantequatres.setRotationPoint(-5F, 9F, -20F);
      quarantequatres.setTextureSize(128, 64);
      setRotation(quarantequatres, 0F, 0F, 0F);
      quarantecinq = new ModelRenderer(this, 18, 27);
      quarantecinq.addBox(0F, 0F, 0F, 1, 8, 22);
      quarantecinq.setRotationPoint(-14F, 8F, -11F);
      quarantecinq.setTextureSize(128, 64);
      setRotation(quarantecinq, 0F, 0F, 0F);
      quarantesix = new ModelRenderer(this, 18, 27);
      quarantesix.addBox(0F, 0F, 0F, 1, 8, 24);
      quarantesix.setRotationPoint(12F, 8F, -12F);
      quarantesix.setTextureSize(128, 64);
      setRotation(quarantesix, 0F, 0F, 0F);
      quarantesept = new ModelRenderer(this, 70, 0);
      quarantesept.addBox(0F, 0F, 0F, 1, 7, 28);
      quarantesept.setRotationPoint(-14F, 17F, -14F);
      quarantesept.setTextureSize(128, 64);
      setRotation(quarantesept, 0F, 0F, 0F);
      quarantehuit = new ModelRenderer(this, 40, 0);
      quarantehuit.addBox(0F, 0F, 0F, 27, 7, 28);
      quarantehuit.setRotationPoint(-13F, 17F, -14F);
      quarantehuit.setTextureSize(128, 64);
      setRotation(quarantehuit, 0F, 0F, 0F);
  }

  public void renderAll()
  {
    this.un.render(0.0625F);
    this.deux.render(0.0625F);
    this.trois.render(0.0625F);
    this.quatres.render(0.0625F);
    this.cinq.render(0.0625F);
    this.six.render(0.0625F);
    this.sept.render(0.0625F);
    this.huit.render(0.0625F);
    this.neuf.render(0.0625F);
    this.dix.render(0.0625F);
    this.onze.render(0.0625F);
    this.douze.render(0.0625F);
    this.quatorze.render(0.0625F);
    this.quinze.render(0.0625F);
    this.seize.render(0.0625F);
    this.douze.render(0.0625F);
    this.treize.render(0.0625F);
    this.quatorze.render(0.0625F);
    this.quinze.render(0.0625F);
    this.seize.render(0.0625F);
    this.dixsept.render(0.0625F);
    this.dixneuf.render(0.0625F);
    this.vingt.render(0.0625F);
    this.vingtetun.render(0.0625F);
    this.vingtdeux.render(0.0625F);
    this.vingttrois.render(0.0625F);
    this.vingtquatres.render(0.0625F);
    this.vingtcinq.render(0.0625F);
    this.vingtsix.render(0.0625F);
    this.vingtsept.render(0.0625F);
    this.vingthuit.render(0.0625F);
    this.vingtneuf.render(0.0625F);
    this.trente.render(0.0625F);
    this.trenteetun.render(0.0625F);
    this.trentedeux.render(0.0625F);
    this.trentetrois.render(0.0625F);
    this.trentequatres.render(0.0625F);
    this.trentecinq.render(0.0625F);
    this.trentesix.render(0.0625F);
    this.trentesept.render(0.0625F);
    this.trentehuit.render(0.0625F);
    this.trenteneuf.render(0.0625F);
    this.quarante.render(0.0625F);
    this.quaranteetun.render(0.0625F);
    this.quarantedeux.render(0.0625F);
    this.quarantetrois.render(0.0625F);
    this.quarantequatres.render(0.0625F);
    this.quarantecinq.render(0.0625F);
    this.quarantesix.render(0.0625F);
    this.quarantesept.render(0.0625F);
    this.quarantehuit.render(0.0625F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}