package com.minefus.degraduck.proxy;

import com.minefus.degraduck.common.Minefus;
import com.minefus.degraduck.entity.EntityAggressiveArakne;
import com.minefus.degraduck.entity.EntityArakne;
import com.minefus.degraduck.entity.EntityBlackBoufton;
import com.minefus.degraduck.entity.EntityBlackYoungBoufton;
import com.minefus.degraduck.entity.EntityBlueLarva;
import com.minefus.degraduck.entity.EntityBluePiou;
import com.minefus.degraduck.entity.EntityBluePioussin;
import com.minefus.degraduck.entity.EntityBlueUnripeLarva;
import com.minefus.degraduck.entity.EntityBouftou;
import com.minefus.degraduck.entity.EntityChampchamp;
import com.minefus.degraduck.entity.EntityChiefOfWarBouftou;
import com.minefus.degraduck.entity.EntityCraquebille;
import com.minefus.degraduck.entity.EntityCraqueboule;
import com.minefus.degraduck.entity.EntityFairfulMoskito;
import com.minefus.degraduck.entity.EntityGreenLarva;
import com.minefus.degraduck.entity.EntityGreenPiou;
import com.minefus.degraduck.entity.EntityGreenPioussin;
import com.minefus.degraduck.entity.EntityGreenUnripeLarva;
import com.minefus.degraduck.entity.EntityLittleBouftou;
import com.minefus.degraduck.entity.EntityLittleChiefOfWarBouftou;
import com.minefus.degraduck.entity.EntityLittleTofu;
import com.minefus.degraduck.entity.EntityLittleWildTournesol;
import com.minefus.degraduck.entity.EntityMilimilou;
import com.minefus.degraduck.entity.EntityMoskito;
import com.minefus.degraduck.entity.EntityOrangeLarva;
import com.minefus.degraduck.entity.EntityOrangeUnripeLarva;
import com.minefus.degraduck.entity.EntityPinkPiou;
import com.minefus.degraduck.entity.EntityPinkPioussin;
import com.minefus.degraduck.entity.EntityPurplePiou;
import com.minefus.degraduck.entity.EntityPurplePioussin;
import com.minefus.degraduck.entity.EntityRedPiou;
import com.minefus.degraduck.entity.EntityRedPioussin;
import com.minefus.degraduck.entity.EntityRoyalBouftou;
import com.minefus.degraduck.entity.EntitySickedArakne;
import com.minefus.degraduck.entity.EntitySickedTofu;
import com.minefus.degraduck.entity.EntityTofu;
import com.minefus.degraduck.entity.EntityUnripeArakne;
import com.minefus.degraduck.entity.EntityVulnerableChampchamp;
import com.minefus.degraduck.entity.EntityWhiteBoufton;
import com.minefus.degraduck.entity.EntityWhiteYoungBoufton;
import com.minefus.degraduck.entity.EntityWildTournesol;
import com.minefus.degraduck.entity.EntityYellowPiou;
import com.minefus.degraduck.entity.EntityYellowPioussin;
import com.minefus.degraduck.events.MinefusKeyHandler;
import com.minefus.degraduck.models.mobs.ModelArakne;
import com.minefus.degraduck.models.mobs.ModelBlackBoufton;
import com.minefus.degraduck.models.mobs.ModelBluePiou;
import com.minefus.degraduck.models.mobs.ModelBouftou;
import com.minefus.degraduck.models.mobs.ModelChampChamp;
import com.minefus.degraduck.models.mobs.ModelChiefOfWarBouftou;
import com.minefus.degraduck.models.mobs.ModelCraquebille;
import com.minefus.degraduck.models.mobs.ModelGreenPiou;
import com.minefus.degraduck.models.mobs.ModelLarva;
import com.minefus.degraduck.models.mobs.ModelMilimilou;
import com.minefus.degraduck.models.mobs.ModelMoskito;
import com.minefus.degraduck.models.mobs.ModelPinkPiou;
import com.minefus.degraduck.models.mobs.ModelPurplePiou;
import com.minefus.degraduck.models.mobs.ModelRedPiou;
import com.minefus.degraduck.models.mobs.ModelRoyalBouftou;
import com.minefus.degraduck.models.mobs.ModelTofu;
import com.minefus.degraduck.models.mobs.ModelWhiteBoufton;
import com.minefus.degraduck.models.mobs.ModelWildTournesol;
import com.minefus.degraduck.models.mobs.ModelYellowPiou;
import com.minefus.degraduck.render.items.RenderBouftouHammer;
import com.minefus.degraduck.render.items.RenderMousseSpade;
import com.minefus.degraduck.render.items.RenderRoyalBouftouSword;
import com.minefus.degraduck.render.mobs.RenderAggressiveArakne;
import com.minefus.degraduck.render.mobs.RenderArakne;
import com.minefus.degraduck.render.mobs.RenderBlackBoufton;
import com.minefus.degraduck.render.mobs.RenderBlackYoungBoufton;
import com.minefus.degraduck.render.mobs.RenderBlueLarva;
import com.minefus.degraduck.render.mobs.RenderBluePiou;
import com.minefus.degraduck.render.mobs.RenderBluePioussin;
import com.minefus.degraduck.render.mobs.RenderBlueUnripeLarva;
import com.minefus.degraduck.render.mobs.RenderBouftou;
import com.minefus.degraduck.render.mobs.RenderChampChamp;
import com.minefus.degraduck.render.mobs.RenderChiefOfWar;
import com.minefus.degraduck.render.mobs.RenderCraquebille;
import com.minefus.degraduck.render.mobs.RenderCraqueboule;
import com.minefus.degraduck.render.mobs.RenderFairfulMoskito;
import com.minefus.degraduck.render.mobs.RenderGreenLarva;
import com.minefus.degraduck.render.mobs.RenderGreenPiou;
import com.minefus.degraduck.render.mobs.RenderGreenPioussin;
import com.minefus.degraduck.render.mobs.RenderGreenUnripeLarva;
import com.minefus.degraduck.render.mobs.RenderLittleBouftou;
import com.minefus.degraduck.render.mobs.RenderLittleChiefOfWarBouftou;
import com.minefus.degraduck.render.mobs.RenderLittleTofu;
import com.minefus.degraduck.render.mobs.RenderLittleWildTournesol;
import com.minefus.degraduck.render.mobs.RenderMilimilou;
import com.minefus.degraduck.render.mobs.RenderMoskito;
import com.minefus.degraduck.render.mobs.RenderOrangeLarva;
import com.minefus.degraduck.render.mobs.RenderOrangeUnripeLarva;
import com.minefus.degraduck.render.mobs.RenderPinkPiou;
import com.minefus.degraduck.render.mobs.RenderPinkPioussin;
import com.minefus.degraduck.render.mobs.RenderPurplePiou;
import com.minefus.degraduck.render.mobs.RenderPurplePioussin;
import com.minefus.degraduck.render.mobs.RenderRedPiou;
import com.minefus.degraduck.render.mobs.RenderRedPioussin;
import com.minefus.degraduck.render.mobs.RenderRoyalBouftou;
import com.minefus.degraduck.render.mobs.RenderSickedArakne;
import com.minefus.degraduck.render.mobs.RenderSickedTofu;
import com.minefus.degraduck.render.mobs.RenderTofu;
import com.minefus.degraduck.render.mobs.RenderUnripeArakne;
import com.minefus.degraduck.render.mobs.RenderVulnerableChampChamp;
import com.minefus.degraduck.render.mobs.RenderWhiteBoufton;
import com.minefus.degraduck.render.mobs.RenderWhiteYoungBoufton;
import com.minefus.degraduck.render.mobs.RenderWildTournesol;
import com.minefus.degraduck.render.mobs.RenderYellowPiou;
import com.minefus.degraduck.render.mobs.RenderYellowPioussin;

import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.FMLCommonHandler;
import net.minecraftforge.client.MinecraftForgeClient;

public class ClientProxy extends CommonProxy
{
    public void registerRender()
    {
        FMLCommonHandler.instance().bus().register(new MinefusKeyHandler());
        MinecraftForgeClient.registerItemRenderer(Minefus.bouftouHammer, new RenderBouftouHammer());
        MinecraftForgeClient.registerItemRenderer(Minefus.mousseSpade, new RenderMousseSpade());
        MinecraftForgeClient.registerItemRenderer(Minefus.royalBouftouSword, new RenderRoyalBouftouSword());
        RenderingRegistry.registerEntityRenderingHandler(EntityArakne.class, new RenderArakne(new ModelArakne(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityGreenLarva.class, new RenderGreenLarva(new ModelLarva(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityChampchamp.class, new RenderChampChamp(new ModelChampChamp(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityTofu.class, new RenderTofu(new ModelTofu(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityMoskito.class, new RenderMoskito(new ModelMoskito(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityOrangeLarva.class, new RenderOrangeLarva(new ModelLarva(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlueLarva.class, new RenderBlueLarva(new ModelLarva(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBouftou.class, new RenderBouftou(new ModelBouftou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityWhiteBoufton.class, new RenderWhiteBoufton(new ModelWhiteBoufton(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlackBoufton.class, new RenderBlackBoufton(new ModelBlackBoufton(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityGreenPiou.class, new RenderGreenPiou(new ModelGreenPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBluePiou.class, new RenderBluePiou(new ModelBluePiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityYellowPiou.class, new RenderYellowPiou(new ModelYellowPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityPinkPiou.class, new RenderPinkPiou(new ModelPinkPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityRedPiou.class, new RenderRedPiou(new ModelRedPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityPurplePiou.class, new RenderPurplePiou(new ModelPurplePiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityCraquebille.class, new RenderCraquebille(new ModelCraquebille(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityWildTournesol.class, new RenderWildTournesol(new ModelWildTournesol(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySickedArakne.class, new RenderSickedArakne(new ModelArakne(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityUnripeArakne.class, new RenderUnripeArakne(new ModelArakne(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityAggressiveArakne.class, new RenderAggressiveArakne(new ModelArakne(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityGreenUnripeLarva.class, new RenderGreenUnripeLarva(new ModelLarva(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityVulnerableChampchamp.class, new RenderVulnerableChampChamp(new ModelChampChamp(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntitySickedTofu.class, new RenderSickedTofu(new ModelTofu(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityLittleTofu.class, new RenderLittleTofu(new ModelTofu(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityFairfulMoskito.class, new RenderFairfulMoskito(new ModelMoskito(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityOrangeUnripeLarva.class, new RenderOrangeUnripeLarva(new ModelLarva(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlueUnripeLarva.class, new RenderBlueUnripeLarva(new ModelLarva(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityLittleBouftou.class, new RenderLittleBouftou(new ModelBouftou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityWhiteYoungBoufton.class, new RenderWhiteYoungBoufton(new ModelWhiteBoufton(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBlackYoungBoufton.class, new RenderBlackYoungBoufton(new ModelBlackBoufton(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityGreenPioussin.class, new RenderGreenPioussin(new ModelGreenPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityBluePioussin.class, new RenderBluePioussin(new ModelBluePiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityYellowPioussin.class, new RenderYellowPioussin(new ModelYellowPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityPinkPioussin.class, new RenderPinkPioussin(new ModelPinkPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityRedPioussin.class, new RenderRedPioussin(new ModelRedPiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityPurplePioussin.class, new RenderPurplePioussin(new ModelPurplePiou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityCraqueboule.class, new RenderCraqueboule(new ModelCraquebille(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityMilimilou.class, new RenderMilimilou(new ModelMilimilou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityChiefOfWarBouftou.class, new RenderChiefOfWar(new ModelChiefOfWarBouftou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityLittleWildTournesol.class, new RenderLittleWildTournesol(new ModelWildTournesol(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityRoyalBouftou.class, new RenderRoyalBouftou(new ModelRoyalBouftou(), 0.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityLittleChiefOfWarBouftou.class, new RenderLittleChiefOfWarBouftou(new ModelChiefOfWarBouftou(), 0.5F));
    }
}